#!/usr/bin/env perl

use 5.006;

use strict;
use warnings;

use App::Warning::Diagnostics qw{ builtins warning_diagnostics };
use Getopt::Long 2.33 qw{ :config auto_version };
use Pod::Usage;

our $VERSION = '0.000_012';

my %opt;

GetOptions( \%opt,
    qw{ primitive! },
    help => sub { pod2usage( { -verbose => 2 } ) },
) or pod2usage( { -verbose => 0 } );

@ARGV
    or @ARGV = ( sort( builtins() ) );

foreach my $category ( @ARGV ) {
    not $opt{primitive}
	or 1 == unpack '%32b*', $warnings::Bits{$category}
	or next;
    my $count =()= warning_diagnostics( $category );
    say "$category\t$count";
}

__END__

=head1 TITLE

count-diagnostics - Count the diagnostics associated with each warning category

=head1 SYNOPSIS

 count-diagnostics
 count-diagnostics io
 count-diagnostics --help
 count-diagnostics --version

=head1 OPTIONS

=head2 --help

This option displays the documentation for this script. The script then
exits.

=head2 --primitive

If this Boolean option is asserted, group categories like C<'io'> and
C<'experimental'> are not included in the output.

The default is C<--no-primitive>.

=head2 --version

This option displays the version of this script. The script then exits.

=head1 DETAILS

This Perl script counts the number of diagnostics associated with each
warning category specified on the command line, and displays them to
standard out. If none are specified, all are reported.

=head1 AUTHOR

Thomas R. Wyant, III F<wyant at cpan dot org>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2021 by Thomas R. Wyant, III

This program is free software; you can redistribute it and/or modify it
under the same terms as Perl 5.10.0. For more details, see the full text
of the licenses in the directory LICENSES.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

=cut

# ex: set textwidth=72 :
